In [1]:
# importando bibliotecas
import pandas as pd
import numpy as np

In [2]:
df_2019 = pd.read_csv('../../Dados/Censo/populacao_raca_2019.csv')
df_2020 = pd.read_csv('../../Dados/Censo/populacao_raca_2020.csv')
df_2021 = pd.read_csv('../../Dados/Censo/populacao_raca_2021.csv')

In [7]:
df_populacao = pd.concat([df_2019,df_2020,df_2021],ignore_index=True)
df_populacao

,uf,total_pessoas,perc_branca,perc_preta,perc_parda,perc_preta_ou_parda,ano
0,RO,1767,28.3,7.1,63.5,70.6,2019
1,AC,865,18.3,6.0,74.2,80.1,2019
2,AM,3983,15.5,3.3,78.8,82.1,2019
3,RR,540,19.8,8.5,65.1,73.6,2019
4,PA,8561,18.4,8.3,72.3,80.7,2019
...,...,...,...,...,...,...,...
76,RS,11448,80.8,5.7,13.2,18.9,2021
77,MS,2768,43.0,6.1,49.6,55.7,2021
78,MT,3512,29.4,9.7,59.8,69.4,2021
79,GO,7209,32.5,8.3,58.7,67.0,2021
80,DF,3092,38.1,10.8,50.1,60.9,2021

In [8]:
# Como os valores sÃ£o para cada 1000 pessoas, multiplicamos os valores populacionais por 1000
df_populacao['total_pessoas'] = df_populacao['total_pessoas'] * 1000


# Criamos novas colunas dos dados que estÃ£o em formato percentual para numÃ©rico
df_populacao['pop_branca'] = round(((df_populacao['perc_branca']/100)) * df_populacao['total_pessoas'],0)
df_populacao['pop_preta'] = round(((df_populacao['perc_preta']/100)) * df_populacao['total_pessoas'],0)
df_populacao['pop_parda'] = round(((df_populacao['perc_parda']/100)) * df_populacao['total_pessoas'],0)
df_populacao['pop_preta_ou_parda'] = round(((df_populacao['perc_preta_ou_parda']/100)) * df_populacao['total_pessoas'],0)

df_populacao

,uf,total_pessoas,perc_branca,perc_preta,perc_parda,perc_preta_ou_parda,ano,pop_branca,pop_preta,pop_parda,pop_preta_ou_parda
0,RO,1767000,28.3,7.1,63.5,70.6,2019,500061.0,125457.0,1122045.0,1247502.0
1,AC,865000,18.3,6.0,74.2,80.1,2019,158295.0,51900.0,641830.0,692865.0
2,AM,3983000,15.5,3.3,78.8,82.1,2019,617365.0,131439.0,3138604.0,3270043.0
3,RR,540000,19.8,8.5,65.1,73.6,2019,106920.0,45900.0,351540.0,397440.0
4,PA,8561000,18.4,8.3,72.3,80.7,2019,1575224.0,710563.0,6189603.0,6908727.0
...,...,...,...,...,...,...,...,...,...,...,...
76,RS,11448000,80.8,5.7,13.2,18.9,2021,9249984.0,652536.0,1511136.0,2163672.0
77,MS,2768000,43.0,6.1,49.6,55.7,2021,1190240.0,168848.0,1372928.0,1541776.0
78,MT,3512000,29.4,9.7,59.8,69.4,2021,1032528.0,340664.0,2100176.0,2437328.0
79,GO,7209000,32.5,8.3,58.7,67.0,2021,2342925.0,598347.0,4231683.0,4830030.0
80,DF,3092000,38.1,10.8,50.1,60.9,2021,1178052.0,333936.0,1549092.0,1883028.0

In [9]:
#Incluindo uma coluna com os nomes dos estados em extenso

df_populacao['estado'] = df_populacao['uf']
mapeamento = {
    "AC":"Acre",
    "AL":"Alagoas",
    "AP":"AmapÃ¡",
    "AM":"Amazonas",
    "BA":"Bahia",
    "CE":"CearÃ¡",
    "DF":"Distrito Federal",
    "ES":"EspÃ­rito Santo",
    "GO":"GoiÃ¡s",
    "MA":"MaranhÃ£o",
    "MT":"Mato Grosso",
    "MS":"Mato Grosso do Sul",
    "MG":"Minas Gerais",
    "PA":"ParÃ¡",
    "PB":"ParaÃ­ba",
    "PR":"ParanÃ¡",
    "PE":"Pernambuco",
    "PI":"PiauÃ­",
    "RJ":"Rio de Janeiro",
    "RN":"Rio Grande do Norte",
    "RS":"Rio Grande do Sul",
    "RO":"RondÃ´nia",
    "RR":"Roraima",
    "SC":"Santa Catarina",
    "SP":"SÃ£o Paulo",
    "SE":"Sergipe",
    "TO":"Tocantins"
    
}

df_populacao['estado'] = df_populacao['estado'].replace(mapeamento)
df_populacao

,uf,total_pessoas,perc_branca,perc_preta,perc_parda,perc_preta_ou_parda,ano,pop_branca,pop_preta,pop_parda,pop_preta_ou_parda,estado
0,RO,1767000,28.3,7.1,63.5,70.6,2019,500061.0,125457.0,1122045.0,1247502.0,RondÃ´nia
1,AC,865000,18.3,6.0,74.2,80.1,2019,158295.0,51900.0,641830.0,692865.0,Acre
2,AM,3983000,15.5,3.3,78.8,82.1,2019,617365.0,131439.0,3138604.0,3270043.0,Amazonas
3,RR,540000,19.8,8.5,65.1,73.6,2019,106920.0,45900.0,351540.0,397440.0,Roraima
4,PA,8561000,18.4,8.3,72.3,80.7,2019,1575224.0,710563.0,6189603.0,6908727.0,ParÃ¡
...,...,...,...,...,...,...,...,...,...,...,...,...
76,RS,11448000,80.8,5.7,13.2,18.9,2021,9249984.0,652536.0,1511136.0,2163672.0,Rio Grande do Sul
77,MS,2768000,43.0,6.1,49.6,55.7,2021,1190240.0,168848.0,1372928.0,1541776.0,Mato Grosso do Sul
78,MT,3512000,29.4,9.7,59.8,69.4,2021,1032528.0,340664.0,2100176.0,2437328.0,Mato Grosso
79,GO,7209000,32.5,8.3,58.7,67.0,2021,2342925.0,598347.0,4231683.0,4830030.0,GoiÃ¡s
80,DF,3092000,38.1,10.8,50.1,60.9,2021,1178052.0,333936.0,1549092.0,1883028.0,Distrito Federal

In [10]:
# Melt the DataFrame to transform it into the desired format
melted_df = pd.melt(df_populacao, id_vars=['ano', 'uf','estado'], value_vars=['pop_branca', 'pop_preta', 'pop_parda'],
                    var_name='racacor', value_name='TOTAL')

melted_df

      ano  uf              estado     racacor      TOTAL
0    2019  RO            RondÃ´nia  pop_branca   500061.0
1    2019  AC                Acre  pop_branca   158295.0
2    2019  AM            Amazonas  pop_branca   617365.0
3    2019  RR             Roraima  pop_branca   106920.0
4    2019  PA                ParÃ¡  pop_branca  1575224.0
..    ...  ..                 ...         ...        ...
238  2021  RS   Rio Grande do Sul   pop_parda  1511136.0
239  2021  MS  Mato Grosso do Sul   pop_parda  1372928.0
240  2021  MT         Mato Grosso   pop_parda  2100176.0
241  2021  GO               GoiÃ¡s   pop_parda  4231683.0
242  2021  DF    Distrito Federal   pop_parda  1549092.0

[243 rows x 5 columns]

In [11]:
# TransformaÃ§Ã£o do data frame em um novo agrupado pelos atributos que desejamos
melted_df['percentage_of_total'] = (melted_df['TOTAL'] / melted_df.groupby(['ano', 'uf','estado'])['TOTAL'].transform('sum')) * 100
melted_df

      ano  uf              estado     racacor      TOTAL  percentage_of_total
0    2019  RO            RondÃ´nia  pop_branca   500061.0            28.614762
1    2019  AC                Acre  pop_branca   158295.0            18.578680
2    2019  AM            Amazonas  pop_branca   617365.0            15.881148
3    2019  RR             Roraima  pop_branca   106920.0            21.199143
4    2019  PA                ParÃ¡  pop_branca  1575224.0            18.585859
..    ...  ..                 ...         ...        ...                  ...
238  2021  RS   Rio Grande do Sul   pop_parda  1511136.0            13.239719
239  2021  MS  Mato Grosso do Sul   pop_parda  1372928.0            50.253293
240  2021  MT         Mato Grosso   pop_parda  2100176.0            60.465116
241  2021  GO               GoiÃ¡s   pop_parda  4231683.0            58.994975
242  2021  DF    Distrito Federal   pop_parda  1549092.0            50.606061

[243 rows x 6 columns]

In [12]:
# ConversÃ£o do dataframe em CSV
melted_df.to_csv("../Dados/Dataset_Power_BI/Dados_Censo.csv")